app:
  translation-api-url: ''
  ocr-api-key: ''
  timezone-api-key: ''
  bot:
    token: ''
    username: ''

cron:
  expecting-input-cleanup: "*/5 * * * * *"

spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/UtilsBotDB
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
#    show-sql: true
    open-in-view: false
    properties:
#      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      #hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.cache.infinispan.statistics: false
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.infinispan.entity.expiration.lifespan: 600000 #10 min
      hibernate.cache.infinispan.entity.memory.size: 124
      hibernate.cache.infinispan.jgroups_cfg: default-configs/default-jgroups-tcp.xml
    hibernate:
      ddl-auto: none
  cache:
    type: infinispan
  liquibase:
    change-log: classpath:config/liquibase/master.xml

logging:
  config: classpath:logback-spring.xml

